---
- name: Change chrony configuration
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    backup: true
  notify: restart chrony

- name: Sync Clock to IST
  ansible.builtin.shell: sudo timedatectl set-timezone Asia/Kolkata