---
- name: Update apt repo and cache on all Debian/Ubuntu boxes
  ansible.builtin.apt: 
    update_cache: true
    force_apt_get: true 
    cache_valid_time: 3600

- name: Upgrade all packages on servers
  ansible.builtin.apt: 
    upgrade: true 
    force_apt_get: true
    
- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required by overcloud host
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible for kernel updates"
    connect_timeout: 5
    reboot_timeout: 180
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required_file.stat.exists == true  